// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(CookieDbContext))]
    [Migration("20200302181748_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Data.Cookie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cookies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Message = "fortune: No such file or directory"
                        },
                        new
                        {
                            Id = 2,
                            Message = "A computer scientist is someone who fixes things that aren''t broken."
                        },
                        new
                        {
                            Id = 3,
                            Message = "After enough decimal places, nobody gives a damn."
                        },
                        new
                        {
                            Id = 4,
                            Message = "A bad random number generator: 1, 1, 1, 1, 1, 4.33e+67, 1, 1, 1"
                        },
                        new
                        {
                            Id = 5,
                            Message = "A computer program does what you tell it to do, not what you want it to do."
                        },
                        new
                        {
                            Id = 6,
                            Message = "Emacs is a nice operating system, but I prefer UNIX. — Tom Christaensen"
                        },
                        new
                        {
                            Id = 7,
                            Message = "Any program that runs right is obsolete."
                        },
                        new
                        {
                            Id = 8,
                            Message = "A list is only as strong as its weakest link. — Donald Knuth"
                        },
                        new
                        {
                            Id = 9,
                            Message = "Feature: A bug with seniority."
                        },
                        new
                        {
                            Id = 10,
                            Message = "Computers make very fast, very accurate mistakes."
                        },
                        new
                        {
                            Id = 11,
                            Message = "<script>alert('This should not be displayed in a browser alert box.');</script>"
                        },
                        new
                        {
                            Id = 12,
                            Message = "フレームワークのベンチマーク"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
