global using Data;
global using Google.Protobuf.WellKnownTypes;
global using Grpc;
global using Grpc.Core;
global using Grpc.Net.Client;
global using Microsoft.Extensions.Configuration;
global using System.Net;
global using System.Net.Http.Json;
global using System.Text.Json.Nodes;
